create or replace PROCEDURE OBTENER_PERSONAS_POR_NACIONALIDAD 
(
  NAC IN VARCHAR2 -- nacionalidad
) AS
BEGIN
  FOR PERSONA IN (SELECT * FROM registro WHERE registro.nacionalidad = NAC)
  LOOP
    DBMS_OUTPUT.PUT_LINE(persona.NOMBRE);
  END LOOP;
      
END OBTENER_PERSONAS_POR_NACIONALIDAD;